server:
  port: 8000
  servlet:
    session:
      cookie:
        name: session_isutrain

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOSTNAME:localhost}:${MYSQL_PORT:13306}/${MYSQL_DATABASE:isutrain}?useUnicode=true&useSSL=true&useCharacterEncoding=utf-8&serverTimezone=JST
    username: ${MYSQL_USER:isutrain}
    password: ${MYSQL_PASSWORD:isutrain}

  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    root: debug
