version: '3'

services:

  webapp:
    build:
      context: ..
    image: isucon-9-final-java-webapp
    ports:
      - "8000:8000"

  mysql:
    image: mysql:8
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - "TZ=Asia/Tokyo"
    env_file:
      - "../../.env"
    volumes:
      - ../../mysql_data:/var/lib/mysql
      - ../../sql:/docker-entrypoint-initdb.d
      - ../../mysql/conf.d:/etc/mysql/conf.d
    # development only
    ports:
      - "13306:3306"
