version: '3'

services:
  webapp:
    build:
      context: ..
    image: webapp-webapp
    ports:
      - "8000:8000"
    env_file:
      - "../../.env"
    environment:
      - "MYSQL_HOSTNAME=mysql"
      - "MYSQL_PORT=3306"
    volumes:
      - ../src/main/resources/application.yml:/app/config/application.yml
      - ../src/main/resources/application.yml:/app/resources/application.yml
#    depends_on:
#      - mysql
#
##networks:
#  default:
#    external: false
#    name: isucon-9-final-java
