version: '3'

services:

  mysql:
    image: mysql:8
    container_name: msql8_single
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - "TZ=Asia/Tokyo"
    env_file:
      - "../../.env"
    volumes:
      - ../../sql:/docker-entrypoint-initdb.d
      - ../../mysql/conf.d:/etc/mysql/conf.d
      - ./msql8_single.data:/var/lib/mysql
    # development only
    ports:
      - "3306:3306"
