version: '3'

services:
  webapp:
    build:
      context: ..
    image: eulerlcs/isucon-9-final-java-webapp
    ports:
      - "8000:8000"
    env_file:
      - "../../.env"
    environment:
      - "MYSQL_HOSTNAME=mysql"
      - "MYSQL_PORT=3306"
#    depends_on:
#      - mysql
#
##networks:
#  default:
#    external: false
#    name: isucon-9-final-java
