version: '3'

services:

  webapp:
    build: ./java
    env_file:
      - ".env"
    environment:
      - "PAYMENT_API"
    volumes:
      - ./java/src/main/resources/application.yml:/app/config/application.yml
      - ./java/src/main/resources/application.yml:/app/resources/application.yml
      - /var/log/app/:/app/log/
    links:
      - payment
    ports:
      - "127.0.0.1:8000:8000"
