version: '3'

services:

  webapp:
    build: ./java
    env_file:
      - ".env"
    environment:
      - "PAYMENT_API"
      - MYSQL_PORT: 3306
    links:
      - payment
    ports:
      - "127.0.0.1:8000:8000"
